JoesPetStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JoesPetStore.Models;

namespace JoesPetStore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //var petDetailsViewModel = Facade.FindPurchaseReceipt();
            var petDetailsViewModel = Facade.FindPet();
            return View(petDetailsViewModel);
        }
    }
}

JoesPetStore/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JoesPetStore.Models;

namespace JoesPetStore.Controllers
{
    public class PetController : Controller
    {
        // GET: PetId
        public ActionResult Details()
        {
            var petDetailsViewModel = Facade.FindPet();
            return View(petDetailsViewModel);
        }

        public ActionResult Request()
        {
            var petDetailsViewModel = Facade.FindPet();
            return View(petDetailsViewModel);
        }

        public ActionResult Approve()
        {
            var petDetailsViewModel = Facade.FindPet();
            return View(petDetailsViewModel);
        }

        public ActionResult PurchasePage()
        {
            var petDetailsViewModel = Facade.FindPet();
            return View();
        }

        [HttpPost]
        public ActionResult Purchase(string petid)
        {
            //Facade.CreateReceipt();
            return RedirectToAction("Index", "Home", new { area = "" });
        }


    }
}

JoesPetStore/Views/Home/Index.cshtml
@model JoesPetStore.ViewModels.PetDetailsViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="">
        <h1>Joe's Pet Store</h1>
        <h2>Pet Of The Day!</h2>
        <p>
            Our pet of the day is a lovely Persian cat named Leo.
            Click @Html.ActionLink("here", "Details", "Pet") to see details and take him home.
        </p>
        
    </div>
</div>